spring.application.name=academy
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/academy_jsst
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

#Para empezar rápido: crea/actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto = update
# Buenas prácticas
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Logs SQL (opcional)
spring.jpa.show-sql=true
